# The first instruction is what image we want to base our container on
# We Use an official Python runtime as a parent image
FROM python:3.6
ENV PYTHONUNBUFFERED 1
# create root directory for our project in the container
RUN mkdir /Project1

# Set the working directory to /music_service
WORKDIR /Project1

# Copy the current directory contents into the container at /music_service
ADD . /Project1

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt
